### ISSUE TITLE
Unsupported type returned for User defined datatype..

### ISSUE THREAD

**Issue by olumideolufy29** [ycherkes/OrcaSql#7]
System.ArgumentException: Unsupported type: POST(numeric(16, 0)), null
   at OrcaSql.Core.MetaData.DataColumn..ctor(String name, String type, Boolean nullable)
   at OrcaSql.Core.MetaData.DataColumn..ctor(String name, String type)
   at OrcaSql.Core.MetaData.DatabaseMetaData.GetEmptyDataRow(String tableName, Nullable`1 schemaId)
   at OrcaSql.Core.Engine.DataScanner.ScanTable(String tableName, Nullable`1 schemaId, Boolean isSysTable)
   at OrcaSql.OSMS.Main.LoadTable(String table, Nullable`1 schemaId, Int64 rowCount) in 
.\OrcaSql\src\OrcaSql.OSMS\Main.cs:line 448

**Comment by ycherkes** [comment]
Closed by PR: https://github.com/ycherkes/OrcaSql/pull/8

**Comment by RafeeSoft** [comment]
I had a new issue when try with corrupted database, I would appreciate if you can fix this
System.ArgumentException: Invalid value length: 12
   at OrcaSql.Core.Engine.SqlTypes.SqlUniqueIdentifier.GetValue(Byte[] value) in C:\Plays\OrcaSql\src\OrcaSql.Core\Engine\SqlTypes\SqlUniqueIdentifier.cs:line 26
   at OrcaSql.Core.Engine.Records.Parsers.PrimaryRecordEntityParser.<GetEntities>d__5.MoveNext() in C:\Plays\OrcaSql\src\OrcaSql.Core\Engine\Records\Parsers\PrimaryRecordEntityParser.cs:line 96
   at OrcaSql.Core.Engine.DataScanner.<ScanLinkedDataPages>d__5.MoveNext() in C:\Plays\OrcaSql\src\OrcaSql.Core\Engine\DataScanner.cs:line 62
   at OrcaSql.Core.Engine.DataScanner.<ScanPartition>d__7.MoveNext() in C:\Plays\OrcaSql\src\OrcaSql.Core\Engine\DataScanner.cs:line 143
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at OrcaSql.OSMS.Main.ShowRows(IEnumerable`1 rows, Row schemaRow, String tableName, Int64 rowCount) in C:\Plays\OrcaSql\src\OrcaSql.OSMS\Main.cs:line 514
   at OrcaSql.OSMS.Main.LoadTable(String table, Nullable`1 schemaId, Int64 rowCount) in C:\Plays\OrcaSql\src\OrcaSql.OSMS\Main.cs:line 450

**Comment by ycherkes** [comment]
Hi, @RafeeSoft
The SqlUniqueIdentifier should have 16 bytes length, how can I fix the error if the corrupted db returns 12 bytes only?
